// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DeliverySVCClient is the client API for DeliverySVC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliverySVCClient interface {
	Create(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Delivery, error)
}

type deliverySVCClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliverySVCClient(cc grpc.ClientConnInterface) DeliverySVCClient {
	return &deliverySVCClient{cc}
}

func (c *deliverySVCClient) Create(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Delivery, error) {
	out := new(Delivery)
	err := c.cc.Invoke(ctx, "/delivery.DeliverySVC/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliverySVCServer is the server API for DeliverySVC service.
// All implementations must embed UnimplementedDeliverySVCServer
// for forward compatibility
type DeliverySVCServer interface {
	Create(context.Context, *Product) (*Delivery, error)
	mustEmbedUnimplementedDeliverySVCServer()
}

// UnimplementedDeliverySVCServer must be embedded to have forward compatible implementations.
type UnimplementedDeliverySVCServer struct {
}

func (UnimplementedDeliverySVCServer) Create(context.Context, *Product) (*Delivery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDeliverySVCServer) mustEmbedUnimplementedDeliverySVCServer() {}

// UnsafeDeliverySVCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliverySVCServer will
// result in compilation errors.
type UnsafeDeliverySVCServer interface {
	mustEmbedUnimplementedDeliverySVCServer()
}

func RegisterDeliverySVCServer(s grpc.ServiceRegistrar, srv DeliverySVCServer) {
	s.RegisterService(&DeliverySVC_ServiceDesc, srv)
}

func _DeliverySVC_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliverySVCServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delivery.DeliverySVC/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliverySVCServer).Create(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliverySVC_ServiceDesc is the grpc.ServiceDesc for DeliverySVC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliverySVC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivery.DeliverySVC",
	HandlerType: (*DeliverySVCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DeliverySVC_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/delivery.proto",
}
